import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";

import Navbar from "@/components/navbar/Navbar";
import theme from "./theme";
import AuthProvider from "@/app/lib/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <AuthProvider>
            <body className={`${inter.className} flex flex-col items-center`}>
              {children}
              <Navbar/>
            </body>
          </AuthProvider>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
