import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//declare module "@mui/material/styles" {
//interface Theme {
//palette : {
//primary : {
//main : string;
//}
//secondary : {
//main : string;
//}
//}
//}
//interface ThemeOptions {
//palette? : {
//primary? : {
//main? : string;
//}
//secondary? : {
//main? : string;
//}
//}
//}
//}

//const theme = createTheme({
//palette : {
//primary : {
//main : "#1D5D9B",
//},
//secondary : {
//main : "#FBEEAC",
//}
//}
//});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
